name: unsplash_client
description: Simple application for loading and searching photos from Unsplash.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  dio: ^5.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  logger: ^1.3.0
  photo_view: ^0.14.0
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  retrofit_generator: ^6.0.0+1
  very_good_analysis: ^4.0.0+1
  
flutter:
  uses-material-design: true